include:
  - project: 'ameliend/gitlab-templates'
    file: '/job_templates/pylint.yml'
  - project: 'ameliend/gitlab-templates'
    file: '/job_templates/release.yml'
  - project: 'ameliend/gitlab-templates'
    file: '/job_templates/documentation.yml'

stages:
  - quality
  - release
  - documentation

pylint:
  extends: .pylint
  image: python:3.11-slim
  stage: quality

semantic-release:
  extends: .semantic-release
  image: node
  stage: release

pages:
  extends: .sphinx:deploy
  stage: documentation
