"""Languages library for the VRC Speech Assistant application."""

GOOGLE = {
    "Arabic": "ar-XA",
    "Bulgarian": "bg-BG",
    "Czech": "cs-CZ",
    "Danish": "da-DK",
    "German": "de-DE",
    "Greek": "el-GR",
    "English": "en-EN",
    "Spanish": "es-ES",
    "Estonian": "et-EE",
    "Finnish": "fi-FI",
    "French": "fr-FR",
    "Hungarian": "hu-HU",
    "Indonesian": "id-ID",
    "Italian": "it-IT",
    "Japanese": "ja-JP",
    "Lithuanian": "lt-LT",
    "Latvian": "lv-LV",
    "Dutch": "nl-NL",
    "Polish": "pl-PL",
    "Portuguese": "pt-PT",
    "Portuguese-Brazilian": "pt-BR",
    "Romanian": "ro-RO",
    "Russian": "ru-RU",
    "Slovak": "sk-SK",
    "Slovenian": "sl-SI",
    "Swedish": "sv-SE",
    "Turkish": "tr-TR",
    "Ukrainian": "uk-UA",
    "Chinese": "zh-ZH",
    "Korean": "ko-KR",
    "Norwegian": "no-NO",
}
DEEPL = {
    "Arabic": "AR",
    "Bulgarian": "BG",
    "Czech": "CS",
    "Danish": "DA",
    "German": "DE",
    "Greek": "EL",
    "English": "EN-US",
    "Spanish": "ES",
    "Estonian": "ET",
    "Finnish": "FI",
    "French": "FR",
    "Hungarian": "HU",
    "Indonesian": "ID",
    "Italian": "IT",
    "Japanese": "JA",
    "Korean": "KO",
    "Lithuanian": "LT",
    "Latvian": "LV",
    "Norwegian": "NB",
    "Dutch": "NL",
    "Polish": "PL",
    "Portuguese": "PT-PT",
    "Portuguese-Brazilian": "PT-BR",
    "Romanian": "RO",
    "Russian": "RU",
    "Slovak": "SK",
    "Slovenian": "SL",
    "Swedish": "SV",
    "Turkish": "TR",
    "Ukrainian": "UK",
    "Chinese": "ZH",
}
VOICES = {
    "polly": {
        "Arabic": ["Zeina"],
        "Bulgarian": None,
        "Czech": None,
        "Danish": ["Naja", "Mads"],
        "German": ["Marlene", "Vicki", "Hans"],
        "Greek": None,
        "English": [
            "Ivy",
            "Joanna",
            "Kendra",
            "Kimberly",
            "Salli",
            "Joey",
            "Justin",
            "Matthew",
            "Nicole (Australian)",
            "Russell (Australian)",
            "Amy (British)",
            "Emma (British)",
            "Brian (British)",
            "Aditi (Indian)",
            "Raveena (Indian)",
            "Geraint (Welsh)",
        ],
        "Spanish": [
            "Conchita",
            "Lucia",
            "Enrique",
            "Mia (Mexican)",
            "Lupe (US)",
            "Penelope (US)",
            "Miguel (US)",
        ],
        "Estonian": None,
        "Finnish": None,
        "French": [
            "Celine",
            "Lea",
            "Mathieu",
            "Chantal (Canadian)",
        ],
        "Hungarian": None,
        "Indonesian": None,
        "Italian": ["Carla", "Bianca", "Giorgio"],
        "Japanese": ["Mizuki", "Takumi"],
        "Korean": ["Seoyeon"],
        "Lithuanian": None,
        "Latvian": None,
        "Norwegian": ["Liv"],
        "Dutch": ["Lotte", "Ruben"],
        "Polish": ["Ewa", "Maja", "Jacek", "Jan"],
        "Portuguese": ["Ines", "Cristiano"],
        "Portuguese-Brazilian": ["Camila", "Vitoria", "Ricardo"],
        "Romanian": ["Carmen"],
        "Russian": ["Tatyana", "Maxim"],
        "Slovak": None,
        "Slovenian": None,
        "Swedish": ["Astrid"],
        "Turkish": ["Filiz"],
        "Ukrainian": None,
        "Chinese": ["Zhiyu"],
    },
}
